### ISSUE TITLE
请问取消了代码行交替高亮后还有办法使能吗？非常感谢！

### ISSUE THREAD

**Issue by Freed-Wu** [registor/boxiesty#1]

**Comment by registor** [comment]
暂时我还没有时间进行研究，过后我抽时间研究。

**Comment by muzimuzhi** [comment]
@Freed-Wu 
没懂你说的意思。举个例子可能更容易说清楚。

**Comment by Freed-Wu** [comment]
原先代码背景是奇数行灰色偶数行白色

![2020-02-19 17-38-26 的屏幕截图](https://user-images.githubusercontent.com/32936898/74821636-de3f7580-533e-11ea-93b4-715dd9e5fce8.png)

现在都是白色了

![2020-02-19 17-37-12 的屏幕截图](https://user-images.githubusercontent.com/32936898/74821794-1b0b6c80-533f-11ea-9bac-bc81a999821b.png)

所以请教有没有恢复的方法。。。

另外使用`\documentclass{mcmthesis}`后代码的数字无法显示，你可以测试一下这个错误能不能复现

```
\documentclass{mcmthesis}
\usepackage{boxie}
\begin{document}
	\langCVfile[python][lst:main.py][python]{main.py}{lst/main.py}
\end{document}
```

`main.py`随便输点什么就好:)

**Comment by muzimuzhi** [comment]
在当前项目中，代码交替高亮是在 https://github.com/registor/boxiesty/commit/24bebfef36bb9ff153d6d02eb626118669058d87 中取消的，同时取消的还有对 fvextra 宏包的依赖。

在加载 fvextra 宏包的前提下，我之前的提交 https://github.com/muzimuzhi/fvextra/commit/867c371b9c2ef0e49c49140a3483aae4db191580 直接实现了它。相关讨论见 https://github.com/gpoore/fvextra/issues/8

**Comment by registor** [comment]
目前我还没有研究这一个问题，对不起，我最近工作的事太多。

**Comment by Freed-Wu** [comment]
> 另外使用\documentclass{mcmthesis}后代码的数字无法显示，你可以测试一下这个错误能不能复现

mcmthesis 从 6.2.2 升级到6.3 后该错误消失了。（虽然我用的texlive2019还没更新到这个版本:( ）
